# Generated by Django 4.1 on 2023-04-06 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spj", "0003_rename_image_gallery"),
    ]

    operations = [
        migrations.DeleteModel(name="gallery",),
        migrations.AddField(
            model_name="service",
            name="detail_img2",
            field=models.ImageField(default="1", upload_to="pics"),
            preserve_default=False,
        ),
    ]
