# Generated by Django 4.1 on 2023-04-06 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spj", "0005_gallery"),
    ]

    operations = [
        migrations.RemoveField(model_name="gallery", name="created_at",),
        migrations.AddField(
            model_name="gallery",
            name="desc",
            field=models.TextField(default="1"),
            preserve_default=False,
        ),
    ]
