# Generated by Django 4.1 on 2023-04-07 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spj", "0006_remove_gallery_created_at_gallery_desc"),
    ]

    operations = [
        migrations.CreateModel(
            name="gallery_foundation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="gallery")),
                ("desc", models.TextField()),
            ],
        ),
    ]
