# Generated by Django 4.1 on 2023-03-30 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("card", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="requestcard",
            name="address2",
            field=models.CharField(default="nil", max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="requestcard",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=1,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="requestcard", name="aadhar_card", field=models.IntegerField(),
        ),
    ]
