# Generated by Django 4.1 on 2023-03-30 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("card", "0002_requestcard_address2_requestcard_id_and_more"),
    ]

    operations = [
        migrations.RenameModel(old_name="requestcard", new_name="entry",),
    ]
